name: kanji_dictionary
description: Dart implementation of KANJIDIC, a popular Kanji dictionary used by jisho.org.
version: 1.0.5+1
repository: https://github.com/atn832/kanji_dictionary
homepage: https://www.wafrat.com

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  xml: ^6.2.2

dev_dependencies:
  http: ^0.13.5
  lints: ^2.0.0
  test: ^1.16.0

# Prevent dart pub publish from ignoring this file
false_secrets:
 - /lib/src/kanjidic2xml.dart
