name: kanji_dictionary
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/atn832/kanji_dictionary
homepage: https://www.wafrat.com

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  xml: ^6.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
